export const MAKE_DEPOSIT_REQUEST = 'MAKE_DEPOSIT_REQUEST';
export const MAKE_DEPOSIT_SUCCESS = 'MAKE_DEPOSIT_SUCCESS';
export const MAKE_DEPOSIT_FAIL = 'MAKE_DEPOSIT_FAIL';
export const MAKE_DEPOSIT_RESET = 'MAKE_DEPOSIT_RESET';
